---
# Permissions for end users to edit projects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-editor-role
rules:
  - apiGroups:
      - sentry.kubernetes.jaceys.me
    resources:
      - projects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sentry.kubernetes.jaceys.me
    resources:
      - projects/status
    verbs:
      - get
