
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sentry.kubernetes.jaceys.me
  resources:
  - projectkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sentry.kubernetes.jaceys.me
  resources:
  - projectkeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sentry.kubernetes.jaceys.me
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sentry.kubernetes.jaceys.me
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sentry.kubernetes.jaceys.me
  resources:
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sentry.kubernetes.jaceys.me
  resources:
  - teams/status
  verbs:
  - get
  - patch
  - update
