---
# Permissions for end users to view teams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: team-viewer-role
rules:
  - apiGroups:
      - sentry.kubernetes.jaceys.me
    resources:
      - teams
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - sentry.kubernetes.jaceys.me
    resources:
      - teams/status
    verbs:
      - get
