name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-sentry-operator-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-sentry-operator-
      - name: Install dependencies
        run: |
          go mod tidy
          git diff --exit-code --name-only

  ensure:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-sentry-operator-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-sentry-operator-
      - name: Ensure codegen
        run: |
          make generate manifests
          git add -N . && git diff --exit-code --name-only
      - name: Lint
        run: |
          make fmt
          git diff --exit-code --name-only

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-sentry-operator-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-sentry-operator-
      - name: Install tools
        run: |
          ./scripts/install.sh
      - name: Run tests
        run: make test

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-sentry-operator-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-sentry-operator-
      - name: Build binary
        run: make manager

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: make docker-build
